development:
  adapter: mysql2
  database: ember-hello-world_development
  pool: 5

test:
  adapter: mysql2
  database: ember-hello-world_test
  pool: 5

production:
  adapter: mysql2
  database: ember-hello-world_production
  pool: 5 
